routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/', 'DefaultController@index');
Route::post('/', 'DefaultController@index');

Route::post('/', 'SearchController@search')->name('movie.search');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/movie/add', 'MovieController@add')->name('movie.add');
Route::post('/movie/store', 'MovieController@store')->name('movie.store');
Route::post('/language/store', 'Movie_languageController@store')->name('language.store');
Route::get('/movie/{movie}', 'DefaultController@show')->name('movie');

Route::resource('movies','MovieController');
Route::resource('movie_genres','Movie_genreController');

resources/views/home.blade.php
@extends('layouts.master')

@section('content')
<br>
<div class="container">
    <div class="row">
    <div class="col-sm-6">
        <div class="card">
        <div class="card-body">
            <label for="language">Search by Language :  &nbsp; </label>
                <form class="form" action="{{route('movie.search')}}" method="POST">
                @csrf
                <input type="hidden" class="form-control" name="language" value="language">
                    <div class="form-group">
                        <select class="form-control" name="language_id" id="dropdown-menu">
                        @foreach($languages as $languages)
                            <option value="{{$languages->id}}">{{ $languages->name }}</option>
                        @endforeach    
                        </select>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">SEARCH</button>
                    </div>
                </form>
        </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
        <div class="card-body">
            <label for="genre">Search by Genre :  &nbsp; </label>
                <form class="form" action="{{route('movie.search')}}" method="POST">
                @csrf
                <input type="hidden" class="form-control" name="genre" value="genre">
                    <div class="form-group">
                        <select class="form-control" name="genre_id" id="dropdown-menu">
                        @foreach($genres as $genre)
                            <option value="{{$genre->id}}">{{$genre->name}}</option>
                        @endforeach    
                        </select>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">SEARCH</button>
                    </div>
                </form>
        </div>
        </div>
    </div>
    </div>
</div>

<div class="container">
<br>
<a href="{{route('movie.add')}}"><button type="button" class="btn btn-success">ADD MOVIE</button></a>
</div>

<div class="container">
@if(session('success'))
<br>
<div class="alert alert-success alert-dismissible">
<button type="button" class="close" data-dismiss="alert">&times;</button>
<strong>{{session('success')}}</strong>
</div>
@endif
</div>

<div class="container">
<br>
<table class="table">

<tbody>
@if(count($movies)>0)
@foreach($movies as $movie)
<tr>
<td>Movie : <a href="{{route('movies.show',$movie->id)}}"><strong>{{ $movie->title}}</strong></a> <br>
Release Date : {{ $movie->release_date->format('d M Y') }} <br><br>
<img src="{{url('uploads/movie_posters/'.$movie->poster)}}" style="float:left;object-fit:cover;" class="img-responsive" alt="{{$movie->poster}}">
</tr>
<tr>
<td>
<form action="{{route('movies.destroy',$movie->id)}}" method="POST">
    <input type="hidden" name="_method" value="DELETE">
   	@csrf
   		<button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')">DELETE MOVIE</button>
</form>
</td>
</tr>
<tr><td></td></tr>
@endforeach
@else
<tr>
<td colspan=2>No movies found</td>
</tr>
@endif
</tbody>
</table>

{{ $movies->links() }}
</div>

@endsection

resources/views/movie_add.blade.php
@extends('layouts.master')

@section('content')

<br/>
<div class="container">

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
               <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form class="form" action="{{route('movie.store')}}" method="POST" enctype="multipart/form-data">
@csrf
  <div class="form-group"> 
    <label for="title" class="form-label"><strong>Movie Name :</strong></label>
    <input type="text" class="form-control" name="title" placeholder="Add Movie">
  </div>

  <div class="form-group">
    <label for="description" class="form-label"><strong>Description of the Movie :</strong> </label>
    <textarea class="form-control rounded-0" name="description" rows="8"></textarea>
  </div>

  <div class="form-group">
    <label for="release_date" class="form-label"><strong>Release Date</strong></label>
    <div class="form-group input-group date">
    <input type="date" name="release_date" class="form-control" />               
    <span class="glyphicon glyphicon-calender"></span>
    </div>
  </div>

  <div class="form-group">
  <label for="poster" class="form-label"><strong>Upload Poster</strong></label>
    <input type="file" class="form-control-file" name="poster">
  </div>
 
  <div class="form-group">
  <button type="submit" class="btn btn-primary">Submit</button>
  </div>

</form>

</div>
@endsection

resources/views/movie_show.blade.php
@extends('layouts.master')

@section('content')
<br>

<div class="container">
    <br>
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <table class="table">
    <tbody>

        <tr>
            <td>Movie : <strong>{{ $movie->title }}</strong></td>
        </tr>

        <tr>
            <td><img src="{{url('uploads/movie_posters/'.$movie->poster)}}" class="img-responsive" alt="{{$movie->poster}}"></td>
        </tr>

        <tr>
        <td>
            @if($language)
            Language : {{ $language }}
            @else
                @auth
                    <label for="language">Specify Language :  &nbsp; </label>
                        <form class="form" action="{{route('language.store')}}" method="POST">
                        @csrf
                            <input type="hidden" name="movie_id" value="{{ $movie->id}}">
                            <div class="form-group">
                                <select class="form-control" name="language_id" id="dropdown-menu">
                                @foreach($languages as $languages)
                                    <option value="{{$languages->id}}">{{ $languages->name }}</option>
                                @endforeach    
                                </select>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">ADD LANGUAGE</button>
                            </div>
                        </form>
                @endauth
                @guest
                    Language : N/A
                @endguest
            @endif
        </td>
        </tr>

        <tr>
        <td>
            @if(count($genres)>0)
                <ul class="list-inline">
                    <label for="genre">Genre :  &nbsp; </label>
                    @foreach($genres as $genre)
                    <li class="list-inline-item">{{$genre->name}}</li>
                    @endforeach
                </ul> 
            @else
                @auth
                    <label for="genre">Genre :  &nbsp; </label>
                    <form class="form" action="{{route('movie_genres.store')}}" method="POST">
                    @csrf
                        <input type="hidden" name="movie_id" value="{{ $movie->id}}">
                        <div class="form-group">
                            <div class="checkbox">    
                                @foreach($tag as $tag)
                                <label><input type="checkbox" name="tag[]" value="{{$tag->id}}"> {{$tag->name}}</label>&nbsp;  
                                @endforeach
                            </div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">TAG GENRE</button>
                        </div>
                    </form>
                @endauth
                @guest
                    <label for="genre">Genre : N/A </label>
                @endguest             
            @endif
        </td>
        </tr>

        <tr>
        <td>Description : {{ $movie->description}}</td>
        </tr>
    </tbody>
    </table>

   
</div>
@endsection